---
- hosts: localhost
  tasks:
  - name: Build
    include: build_tasks.yml

  - name: Create Flask server container1
    docker_container:
      name: my-flask1
      image: simple_flask:0.1
      ports:
        - "5000:5000"
      env:
        KEY: value1
      command: python hello.py

  - name: Create Flask server container2
    docker_container:
      name: my-flask2
      image: simple_flask:0.1
      ports:
        - "5001:5000"
      env:
        KEY: value2
      command: python hello.py

  - name: Create Flask server container3
    docker_container:
      name: my-flask3
      image: simple_flask:0.1
      ports:
        - "5002:5000"
      env:
        KEY: value3
      command: python hello.py
